spring:
  application:
    name: GenAI

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash-lite
            temperature: 0.7

  logging:
    level:
      root: INFO
      com.genai.java.spring: INFO
      org.springframework.ai: INFO
      org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

application:
  authors: Hugo Rocha
